# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c125da4b7a329eaef2d4838fede2769586b8fc1785a23ada064cb96dc8f58502f4263f355e4bfa865d8cc61a653997396b31545453db921f3a5321b427f0664e

test:
  secret_key_base: dd796a2407256bee280466c0686095f14b194cd426acca7b9383c9c35581912e6abd77b22c44216d7d5be2c939366faad89a04c1bc06e7ed106bb2a36bc2be71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
